myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]
handler500 = views.my_customized_server_error

polls/urls.py
from django.urls import path
from polls import views
from django.contrib.auth import login, logout

app_name="polls"
urlpatterns = [
    path('new', views.new, name='new'),
    path('',views.account_login,name='login'),
    path('logout',views.account_logout,name='logout'),
    path('create',views.create_account,name='create_account'),
    path('user',views.username,name='name'),
    path('del/<int:td_id>',views.td_del,name='td_del'),
    path('test_login',views.test_login, name='test_login')

]

polls/models.py
from django.db import models
from django.utils import timezone
import uuid
# Create your models here.



class Record(models.Model):
    user = models.CharField(max_length=50,default='',null=True,blank=True)
    kill = models.IntegerField()
    death = models.IntegerField()
    score = models.IntegerField()
    DateTime = models.DateTimeField(default=timezone.now)

polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Record
from .form import UserForm, UserCreateForm, LoginForm
from django.views.generic import CreateView, TemplateView
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth.models import User
from django.utils import timezone
import sqlite3
import io
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import base64
import datetime
from django.http import  HttpResponseServerError
from django.views.decorators.csrf import requires_csrf_token

#ログインview
class Create_account(CreateView):
    def post(self, request, *args, **kwargs):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/polls/new')
        return render(request, 'polls/create.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        return  render(request, 'polls/create.html', {'form': form,})

create_account = Create_account.as_view()
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/polls/new')
        return render(request, 'polls/login.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'polls/login.html', {'form': form,})

account_login = Account_login.as_view()

class Account_logout(View):
    def get(self, request, *args, **kwargs):
       logout(request)
       return render(request,'polls/index.html')
account_logout = Account_logout.as_view()

class Username(View):
    def get(self, request, *args,**kwargs):
        user = self.request.user
        return HttpResponse({user})
username = Username.as_view()
#テストユーザでログイン
def test_login(request):
    test_user=authenticate(username='testuser1',password='test!"#$')
    login(request,test_user)
    return redirect('/polls/new')
#メイン画面の関数
@login_required
def new(request):
    user = request.user
    if request.method == 'POST':
        form = UserForm(request.POST)
        record = Record.objects.create(
                                        user = request.user,
                                        kill = request.POST.get('kill'),
                                        death = request.POST.get('death'),
                                        score = request.POST.get('score'),
                                        DateTime = timezone.datetime.now() + timezone.timedelta(hours=9))
     
    kill_graph, death_graph, score_graph, kd_graph = graph_main(user)
    my_dict = {
    'data':None,
    'header':None,
    'form':UserForm(request.POST),
    'kill_graph': kill_graph,
    'death_graph': death_graph,
    'score_graph': score_graph,
    'kd_graph': kd_graph
    }

    data = Record.objects.filter(user=user)
    header=['User','キル数','デス数','スコア数','記録日時','削除']
    my_dict['data'] = data
    my_dict['header'] = header
    return render(request, 'polls/new.html',my_dict)
#表のデータ削除
def td_del(request,td_id):
    td = Record.objects.filter(id=td_id)
    td.delete()
    return redirect('polls:new')
#グラフ作成メイン関数
def graph_main(user):
    kill_list, death_list, score_list, kd_list, week_list = create_list(user)
    for i in range(7):
        week_list[i] = week_list[i].strftime('%m-%d')
    create_graph(kill_list,week_list)
    kill_graph = get_image()
    create_graph(death_list,week_list)
    death_graph = get_image()
    create_graph(score_list,week_list)
    score_graph = get_image()
    create_graph(kd_list,week_list)
    kd_graph = get_image()
    return kill_graph, death_graph, score_graph, kd_graph
    
#以下はグラフ作成の関数群
#キル、デス、スコア、kd、日付の一週間の集計したリストを作成する
def create_list(user):
    week_list = []
    kill_list = []
    death_list = []
    score_list = []
    kd_list = []

    dt_now = datetime.date.today()

    #キル、デス、スコアのリストを二重リストにする。今日の日付から一週間分の日付をリストに保存する
    for i in range(7):
        kill_list.append(list())
        death_list.append(list())
        score_list.append(list())
        week_list.append(dt_now - datetime.timedelta(days = i))


    #今日から一週間の日付のデータをそれぞれ取得しキル、デス、スコアのリストそれぞれにデータを保存する
    for i in range(7):
        data = Record.objects.filter(DateTime__startswith=str(week_list[i]),user=str(user))
        for data in data: # 0:id 1:user 2:kill 3:death 4:score 5: datetime
            kill_list[i].append(data.kill)
            death_list[i].append(data.death)
            score_list[i].append(data.score)

    

    #キル、デス、スコアのリストから日付ごとの値の平均をとり保存する
    def avg_list(list):
        for i in list:
            cnt = 0
            for j in range(len(i)):
                cnt = cnt + int(i[j])
            if len(i) != 0:
                avg = cnt/len(i)
            else:
                avg = 0
            list[list.index(i)] = avg

    avg_list(kill_list)
    avg_list(death_list)
    avg_list(score_list)

    #kdを求めリストに保存する
    for i in range(7):
        if death_list[i] != 0:
            kd = kill_list[i]/death_list[i]
        else:
            kd = 0
        kd_list.append(kd)

    return kill_list, death_list, score_list, kd_list, week_list

#グラフ作成
def create_graph(x_list,y_list):
    plt.cla()
    fig = plt.figure(figsize=(6,5))
    plt.plot(y_list,x_list,label="x",marker='^',markersize=8,color="dimgray",mfc='orange',mec='black')
    for x, y in zip(y_list, x_list):
        plt.text(x, y, round(y,2), ha='center', va='bottom')
    plt.xlabel('date')

#グラフの画像作成
def get_image():
     buffer = io.BytesIO()
     plt.savefig(buffer, format='png')
     image_png = buffer.getvalue()
     graph = base64.b64encode(image_png)
     graph = graph.decode('utf-8')
     buffer.close()
     return graph
#本番環境でもエラーの詳細を表示する関数
@requires_csrf_token
def my_customized_server_error(request, template_name='500.html'):
    import sys
    from django.views import debug
    error_html = debug.technical_500_response(request, *sys.exc_info()).content
    return HttpResponseServerError(error_html)

polls/templates/layout.html
<!doctype html>
<html lang="ja">
{% load static %}
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8"/>
    <meta name="viewport"
     content="width=device-width, initial-scale=1, shring-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}
    <footer class="text-right">
      {% block footer %}{% endblock %}
    </footer>
    {% block extra_js %}{% endblock %}
  </body>
</html>

polls/templates/polls/create.html
{% extends 'layout.html' %} 
{% load static%}
{% block head %}
<link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %} 
{% block content %}
<div class="container-fluid">
  <form method="POST" action="{% url 'polls:create_account' %}">
    {% csrf_token %}
    <h1>アカウント作成</h1>
    <label>ユーザーID</label>
    {{ form.username }} {{ form.username.errors }}
    <label>パスワード</label>
    {{ form.password1 }} {{ form.password1.errors }}
    <label>パスワード(確認)</label>
    {{ form.password2 }} {{ form.password2.errors }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
  <a href="{% url 'polls:login' %}">既存のアカウントでログイン</a>
</div>
{% endblock%}

polls/templates/polls/login.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %} 
{% block content %}
<div class="container-fluid">
  {% if form.errors %}
  <p>ユーザーID, パスワードが一致しません．</p>
  {% endif %}
  <h1>ログインフォーム</h1>
  <form method="POST" action="{% url 'polls:login' %}">
    {% csrf_token %}
    <label>ユーザーID</label>
    {{ form.username }} {{ form.username.errors }}
    <label>パスワード</label>
    {{ form.password }} {{ form.password.errors }}
    <button type="submit" class="btn btn-primary">ログイン</button>
  </form>
  <a href="{% url 'polls:test_login' %}" class="btn btn-success">ゲストログイン</a>
  <a href="{% url 'polls:create_account' %}">アカウントを作成する</a>
</div>
{% endblock %}

polls/templates/polls/new.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/new.css' %}" rel="stylesheet">
{% endblock %} 
{% block title %}Index{% endblock %} 
{% block content %}
<div class="container">
  <h1 class="pt-4">FPS記録画面</h1>
  <div class="row">
    <div class="col-xl-4">
      <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">送信</button>
      </form>
    </div>
    <div class="col-xl-8">
      <h4>アプリケーション説明</h4>
      <p>
        このアプリケーションはFPSの戦績を管理するものです。<br>
        横のフォームでそのマッチでのキル数、デス数、スコア数を入力してください。<br>
        下の表には今までに入力した記録が表示されます。<br>
        表の下にはキル数、デス数、スコア数、kdを日付ごとの平均を表示するグラフが表示されます。
      </p>
      <div><a href="{% url 'polls:login' %}">ログイン画面へ戻る</a></div>
    </div>
  </div>
  <p>{{ kill }}</p>
  <p>{{ death }}</p>
  <p>{{ score }}</p>
  <div style="height: 500px; overflow: auto">
    <table class="table table-bordered">
      <tr>
        {% for h in header %}
        <th>{{h}}</th>
        {% endfor %}
      </tr>
      {% for i in data %}
      <tr>
        <td>{{ i.user }}</td>
        <td>{{ i.kill }}</td>
        <td>{{ i.death }}</td>
        <td>{{ i.score }}</td>
        <td>{{ i.DateTime }}</td>
        <td><button class="btn btn-outline-danger btn-sm"id="del_btn" data-pk="{{ i.id }}" data-url="{% url 'polls:td_del' td_id=i.id %}" onclick="del_click(this)">削除</button></td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <!--モーダルウィンドウ-->
  <div id="modal" class="modal">
          <div class="modal-content">
              <div class="modal-body">
                  <p>ID: <span id="del_pk"></span>を削除しますか?</p>
                  <input type="button" class="btn btn-outline-danger btn-sm" id="close_btn" value="キャンセル">
                  <a href="" class="btn btn-outline-success btn-sm" id= "del_url">OK</a>
              </div>
          </div>
      </div>
  <div class="row">
    <div class="col-xl-6"> 
      <h2>マッチ平均キル数グラフ</h2>
      <img src="data:image/png;base64, {{ kill_graph | safe }} " alt="" />
    </div>
    <div class="col-xl-6">
      <h2>マッチ平均デス数グラフ</h2>
      <img src="data:image/png;base64, {{ death_graph | safe }} " alt="" />
    </div>
  </div>
  <div class="row">
    <div class="col-xl-6">
      <h2>マッチ平均スコア数グラフ</h2>
      <img src="data:image/png;base64, {{ score_graph | safe }} " alt="" />
    </div>
    <div class="col-xl-6">
      <h2>マッチ平均k/dグラフ</h2>
      <img src="data:image/png;base64, {{ kd_graph | safe }} " alt="" />
    </div>
  </div>
</div>
<script src="{% static 'js/new.js' %}"></script>
{% endblock %} 
{% block footer %} 
  <hr>
  <p>© 2021 Ryuki Itatani  All Rights Reserved.</p>
{% endblock %}